### ISSUE TITLE
Bolt failed to start on ubuntu 16.04

### ISSUE THREAD

**Issue by omerlh** [puppetlabs/bolt#1416] opened 2019-11-14 14:34 UTC
## Describe the Bug
I installed bot by following the docs using apt get and when trying to run it I'm getting:
```
bolt
/opt/puppetlabs/bolt/bin/ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /opt/puppetlabs/bolt/lib/libruby.so.2.5)
```

## Expected Behavior
Bolt running
## Steps to Reproduce
1. Install on ubuntu 16.04
2. Try to run it

## Environment
 - Latest
 - Platform Ubuntu 16.04

**Comment by lucywyman** [comment] 2019-11-14 20:02
Hi @omerlh - I don't think this is a problem with Bolt, it looks like you'll just need to upgrade your libc6 package on the system you're installing Bolt on ([source](https://askubuntu.com/questions/421642/libc-so-6-version-glibc-2-14-not-found)):

**Comment by lucywyman** [comment] 2019-11-20 21:02
@omerlh I'm going to close this because I'm reasonably certain it's not an issue with Bolt, as we can't reproduce it with any Bolt version. Let me know if you'd like to keep discussing and we can reopen the issue!

**Closed by lucywyman** 2019-11-20 21:02 UTC
Labels: bug
