### ISSUE TITLE
Support cascading `bolt.yaml` config overrides

### ISSUE THREAD

**Issue by op-ct** [puppetlabs/bolt#1438] opened 2019-11-22 01:32 UTC
## Use Case

From general to specific use cases:

1. As a **system administrator**: I want to configure system-wide defaults for bolt (#759) 
2. As a **user**: I want to configure my private data and personal preferences as _additional_ defaults for bolt
3. As a **bolt project maintainer**: I want to configure project-relevant settings in _addition to_ any of the user and system-wide defaults.

As a **user running bolt**, I want bolt to combine the configurations above, keeping the most specific use case's setting for each top-level option. (#608)

## Describe the Solution You Would Like

A set of cascading `bolt.yaml` config files in system -> user -> project order, with top-level settings in each file overriding the same setting in previous files(s):

![20191121_bolt_inherited_config_files](https://user-images.githubusercontent.com/8979062/69586182-be9ee800-0faf-11ea-95f0-e697043ac5a4.png)

**Comment by adreyer** [comment] 2019-11-25 18:17
The example provided does not just merge top level settings. The ssh config is merged at a secondary level.

It's unclear to me how this is different from #608 .

**Comment by op-ct** [comment] 2019-11-25 23:14
@adreyer:  The original example only merged top-level settings of the _config files,_ then followed through to show the final runtime behavior after CLI options.  I see now that was TMI to concisely describe the merging issue, so I've updated the example to just focus on _just_ that.

This issue is a superset of #608 and #759.  Those issues described different parts of a config file elephant; this is the whole thing.

**Comment by adreyer** [comment] 2019-12-04 23:54
I'm going to close this as a dupe of #608.

**Closed by adreyer** 2019-12-04 23:54 UTC
Labels: Feature
