### ISSUE TITLE
bolt fails if hiera-config is specified but doesn't exist

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#1264] opened 2019-09-30 18:23 UTC
## Describe the Bug

When running `bolt puppetfile install` on a new module, an error occurs if the `bolt.yaml` contains a `hiera-config` key, but the file path that it points to doesn't exist.

## Expected Behavior

Silently ignore the missing hiera config, similar to the behavoir when specifying `inventory` and that file not existing.

## Steps to Reproduce
1. Create a new `bolt.yaml`
```yaml
hiera-config: "/path/that/doesnt/exist/hiera.yaml"
```

2. Run bolt
```shell
bolt puppetfile install
```

3. Get error
```shell
$ bolt puppetfile install
Traceback (most recent call last):
        10: from /opt/puppetlabs/bolt/bin/bolt:23:in `<main>'
         9: from /opt/puppetlabs/bolt/bin/bolt:23:in `load'
         8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.31.1/exe/bolt:9:in `<top (required)>'
         7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.31.1/lib/bolt/cli.rb:118:in `parse'
         6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.31.1/lib/bolt/config.rb:51:in `from_boltdir'
         5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.31.1/lib/bolt/config.rb:51:in `new'
         4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.31.1/lib/bolt/config.rb:88:in `initialize'
         3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.31.1/lib/bolt/config.rb:280:in `validate'
         2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.31.1/lib/bolt/config.rb:280:in `raise'
         1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.31.1/lib/bolt/config.rb:280:in `exception'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.31.1/lib/bolt/error.rb:130:in `initialize': wrong number of arguments (given 1, expected 2) (ArgumentError)
```

## Environment
 - Version: 1.31.0
 - Environment: RHEL 7.7

**Comment by nicklewis** [comment] 2019-09-30 23:20
I predict an issue 3 months from now "Bolt silently ignores hiera-config if it has a typo"...

Does your workflow here involve _later_ creating a `hiera.yaml` in that location or are you just using a standard `bolt.yaml` with a hiera config that may or may not exist? Would it be reasonable to _warn_ if the path is specified but doesn't exist? I would imagine the warning will be annoying if this state is going to persist, but not so much of a problem if you're going to create `hiera.yaml` shortly afterward.

**Comment by nmaludy** [comment] 2019-09-30 23:22
I would even be ok if it straight up errored out with a meaningful error, rather than failing with a cryptic stacktrace.

**Comment by nicklewis** [comment] 2019-09-30 23:29
Oh to be honest I didn't even really look at the stacktrace. That's bad. I opened https://github.com/puppetlabs/bolt/pull/1266 to fix that part.

Now you'll get `Could not read hiera-config file /path/to/nonexistent/file`

**Comment by lucywyman** [comment] 2019-10-15 16:43
We think, for the most part, if you have hiera-config defined but no file that's more likely a mistake than intended behavior. Going to close this since the error message is correct now!

**Closed by lucywyman** 2019-10-15 16:43 UTC
Labels: Bug
