### ISSUE TITLE
Print error result sets from parallelize blocks

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#2977] opened 2021-08-10 17:19 UTC
## Use Case
When running an executor command in a parallelize block, Bolt will not print detailed error messages for any failing results. For example, given the following plan:

```puppet
plan bolt (
  TargetSpec $targets
) {
  $results = parallelize(get_targets($targets)) |$target| {
    run_command('foobar', $target)
  }

  return $results
}
```

A failing result will look like:

```shell
Starting: plan bolt
Starting: command 'foobar' on localhost
Finished: command 'foobar' with 1 failure in 0.01 sec
Error in future '2': run_command 'foobar' failed on 1 target [ID: errored_futures]
Finished: plan bolt in 1.04 sec
parallel block failed on 1 target
  (file: /Users/tom/.puppetlabs/bolt/plans/init.pp, line: 14, column: 10)
```

When running this function outside of a parallelize block, the error result is much more detailed:

```shell
Failed on localhost:
  No such file or directory - foobar
```

If an executor action fails in a parallelize block, the error message should include this additional information.

**Comment by lucywyman** [comment] 2021-08-24 17:59
Ah, so when we create the main plan Fiber [we assign it ID 1](https://github.com/puppetlabs/bolt/blob/main/lib/bolt/pal.rb#L739), but when we check to see if the main plan is still running to know whether to raise a warning or not [we assume the main plan has ID 0](https://github.com/puppetlabs/bolt/blob/main/lib/bolt/fiber_executor.rb#L89), which means that this warning is always raised for any errors when it was intended to only be raised if the main plan had finished.

I think for this we should fix that bug. Once that's fixed, the behavior is the same as running `run_command('foo', $targets, '_catch_errors' => true)`, which assumes that users will run with `--verbose` to see actual error messages.

For example with this plan:
```
plan bolt () {
  run_command('foo', 'localhost', '_catch_errors' => true)
}
```

Will result in this output:
```
lucy ~/githubs/bolt (main) $ be bolt plan run bolt -t localhost
Starting: plan bolt
Starting: command 'foo' on localhost
Finished: command 'foo' with 1 failure in 0.0 sec
Finished: plan bolt in 0.01 sec
Plan completed successfully with no result


lucy ~/githubs/bolt (main) $ be bolt plan run bolt -t localhost --verbose
Starting: plan bolt
Starting: command 'foo' on localhost
Started on localhost...
Failed on localhost:
  No such file or directory - foo
Finished: command 'foo' with 1 failure in 0.0 sec
Finished: plan bolt in 0.01 sec
Plan completed successfully with no result
```

**Closed** 2021-09-09 23:39 UTC
Labels: Bug
