### ISSUE TITLE
Getting Started doc assumes puppetlabs-package is builtin

### ISSUE THREAD

**Issue by cringdahl** [puppetlabs/bolt#2627] opened 2021-02-05 22:42 UTC
## Add a 'bolt module add puppetlabs-package' to the docs 
Maybe it's the 3.0.0 macOS version, but the 'package' task isn't in the builtins. After some digging, I discovered bolt modules and installing them. Honestly, it was a great lesson to learn, but adding it to the lesson would have made it much much easier.

**Comment by beechtom** [comment] 2021-02-05 23:04
@cringdahl Are you installing the Bolt gem or the Bolt package? The gem does not ship with any modules and we do not recommend running Bolt as a gem.

**Comment by cringdahl** [comment] 2021-02-06 05:22
At first the bolt gem that presumably came with some other Puppet package I had (1.4.x), but even the 3.0.0 package via direct download, or via Homebrew, exhibited this problem.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lucywyman** [comment] 2021-02-16 18:39
Is 'package' the only builtin module that's missing? For example, is `service` available? That would be especially weird, since everything just gets installed from the same Puppetfile and the version looks correct. I'd try a `gem uninstall bolt` (which shouldn't affect the package-installed Bolt) just to be safe, but I haven't been able to reproduce this issue with a freshly installed 3.0.0 on OSX 15.

**Comment by cringdahl** [comment] 2021-02-16 19:25
`service` isn't available. I'm not sure what's default, but here's what I have:
```
✔ ~/Code/bolt_test 
13:19 $ bolt module show
Plan Language Modules
  boltlib   (built-in)
  ctrl      (built-in)
  dir       (built-in)
  file      (built-in)
  out       (built-in)
  prompt    (built-in)
  system    (built-in)

/Users/cory2388/Code/bolt_test/modules
  apache   (no metadata)

Project Dependencies
  puppetlabs/package   1.4.0

Packaged Modules
  aggregate        (built-in)
  canary           (built-in)
  puppet_connect   (built-in)
  puppetdb_fact    (built-in)
```

I've got quite the hodgepodge of packages installed, including a PDK that's been `pdk bundle update`d a number of times. Could this have pulled in an incomplete 1.x bolt on principle?

**Comment by lucywyman** [comment] 2021-02-16 22:56
Ah ok, that `packaged_modules` is definitely too short, and indicates to me you're using a Gem install of Bolt. Did you try `gem uninstall bolt`? You might also try `which bolt` and make sure it's pointing to `/opt/puppetlabs/bin/bolt`:
```
lucy ~/githubs/bolt (main) $ which bolt
/usr/local/bin/bolt
lucy ~/githubs/bolt (main) $ ls /usr/local/bin/bolt -l
lrwxrwxrwx 1 root root 24 Feb  4 10:02 /usr/local/bin/bolt -> /opt/puppetlabs/bin/bolt
```

**Comment by cringdahl** [comment] 2021-02-17 16:25
`gem uninstall bolt` did it, I'm seeing a pile of `puppetlabs/*` packages when I do `bolt module show`. 

One thing, though: it takes about 3 seconds to run `bolt`, and about 10 seconds to run `bolt module show`, whereas before it was instantaneous. Is this normal? Could it be the new module list? Could the "Project Dependencies" puppetlabs/package be somehow conflicting with the "Packaged Modules" puppetlabs/package?

**Comment by lucywyman** [comment] 2021-02-19 17:04
I suspect that has more to do with loading the package as opposed to the gem than the specific modules. Are other commands slow, or just `bolt module show`? What OS and Ruby version are you on?

**Comment by lucywyman** [comment] 2021-03-10 19:33
Hm, I think this might be a duplicate of https://github.com/puppetlabs/bolt/issues/2625 - is it ok if I close?

**Comment by lucywyman** [comment] 2021-03-10 19:34
Actually, I think one thing we could do here is provide instructions on our '

**Closed** 2021-03-24 18:55 UTC
Labels: Docs
