### ISSUE TITLE
Merge `bolt.yaml` and `bolt-project.yaml`

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1820] opened 2020-05-14 14:32 UTC
## Use Case
While there are slight differences around these files, bolt.yaml is primarily configuration based while bolt-project.yaml is about the code in a project, there is not really a good reason to have two files in a project. Some values like modulepath make more sense in the bolt-project.yaml file anyway.   

## Describe the Solution You Would Like
Bolt should read bolt.yaml config values from bolt-project.yaml or bolt.yaml. It should issue a deprecation warning if both files are present and prefer values from bolt-project.yaml. 

## Additional Context
We should not yet issue a deprecation warning if only bolt.yaml is present though the file is on a path towards deprecation.

**Comment by beechtom** [comment] 2020-06-12 21:58
Duplicate of #1842 / closed by #1856

**Closed by beechtom** 2020-06-12 21:58 UTC
Labels: Feature
