### ISSUE TITLE
Bolt file upload doesn't work for Windows SSH

### ISSUE THREAD

**Issue by dnvasta** [puppetlabs/bolt#937] opened 2019-04-03 22:07 UTC
If we're connecting to a windows server through an OpenSSH server, bolt file upload/script run doesn't work, seems like there are issue while creating a /tmp directory

I believe https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/ssh/connection.rb needs some modification while creating a tmp directory in case its a windows machine as running "mkdir -m 700 tmppath" won't work in case of Windows machines & throw a "Could not make tempdir: The syntax of the command is incorrect."

**Comment by lucywyman** [comment] 2019-04-05 17:44
Hmm...this is a bit tricky because we need to run the command manually (rather than using `Dir.mkdir`) in order to support running as another user.  I think we'll need to have 'Windows tmpdir' and '*nix tmpdir' subclasses or functions.

I'll make a ticket - I can't promise it'll get prioritized quickly, but I don't think you're the only person running into this or similar issues!

**Comment by adreyer** [comment] 2019-09-25 19:58
duplicate of #813

**Closed by adreyer** 2019-09-25 19:58 UTC
