### ISSUE TITLE
bolt task show bug

### ISSUE THREAD

**Issue by liamjohnsexton** [puppetlabs/bolt#2917] opened 2021-07-07 14:59 UTC
## Describe the Bug
When moving a script (lets say test.ps1) into the 'tasks' folder of a bolt project (without its associated metadata test.json), running `bolt task show` from the CLI correctly shows that the task has no brief description. 

However, if you then move the scripts associated metadata (test.json) into the 'tasks' folder and run `bolt task show` from the CLI again, a description does not show up next to the task, despite the metadata now being with its associated script in the 'tasks' folder of the bolt project (test.ps1 + test.json).

This could end up being a problem for folks creating their script, placing it into the 'tasks' folder, ensuring Bolt has registered that the task is there by running `bolt task show` from the CLI and then deciding to create metadata for the task.

## Expected Behavior
- User is on CLI in the bolt project directory.
- User places script (test.ps1) in 'tasks' folder of the bolt project.
- Runs `bolt task show` from the CLI and sees no description.
- User then places associated metadata (test.json) into 'tasks' folder of the bolt project.
- Runs `bolt task show` from the CLI and sees a brief description next to task.

## Steps to Reproduce
1. Place a script into 'tasks' folder of the bolt project without it's metadata (`tasks/new.ps1`)
2. Go to the CLI, ensure you are in the bolt project directory and run `bolt task show` - you will correctly see no description next to the task and see a list of other tasks.
3. Now place the associated metadata for the script into the 'tasks' folder of the bolt project (`tasks/new.json` + `tasks/new.ps1`).
4. Go back to the CLI, ensuring you are in the bolt project directory and run `bolt task show` - you should expect to see a brief description next to the task in the list of tasks, but do not.

## Environment
 - Could recreate on Bolt 3.11.0 and 3.12.0
 - Using macOS Big Sur version 11.2.3
 - Using iTerm2 Build 3.4.8

## Additional Context
Please ping me on slack at @ Liam Sexton if the above needs more clarification or you need anymore info.

**Comment by lucywyman** [comment] 2021-07-07 15:21
This is a duplicate of https://github.com/puppetlabs/bolt/issues/2915 - it's something we're planning to document, but we don't currently have a good way of preventing this.

**Comment by lucywyman** [comment] 2021-08-02 20:25
@liamjohnsexton This should be fixed in Bolt 3.15.0 (using `--clear-cache`). Let us know if that doesn't work and we can reopen this ticket!

**Closed by lucywyman** 2021-08-02 20:25 UTC
Labels: Bug

**Comment by liamjohnsexton** [comment] 2021-08-03 10:07
Hey Lucy, works perfectly! Thanks!
