### ISSUE TITLE
Windows Install GEM_HOME

### ISSUE THREAD

**Issue by dsisnero** [puppetlabs/bolt#2222] opened 2020-09-24 17:18 UTC
## an existing ruby on system sets GEM_HOME.  Interferes with bolt.bat

Need to unset GEM_HOME in ruby.bat, gem.bat, and bolt.bat

## Expected Behavior
running bolt doesn't look for gems in existing GEM_HOME
## Steps to Reproduce

Installed ruby from scoop which sets GEM_HOME.  need to unset it 

bolt.bat should be the following to clear GEM_home
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
ECHO.This version of Ruby has not been built with support for Windows 95/98/Me.
GOTO :EOF
:WinNT
SET GEM_HOME=
SET RUBY_EXE_PATH="%~dp0ruby.exe"
@%RUBY_EXE_PATH% "%~dpn0" %*

**Comment by jpogran** [comment] 2020-09-28 19:14
@dsisnero are you running bolt from the packaged version on windows? Or through a gem install?

**Comment by dsisnero** [comment] 2020-09-28 22:44
I use scoop instead of chocolatey for installs because I like the ability to install with user rights.  I use scoop to install ruby and also to install puppet-bolt.  The GEM_HOME env variable from ruby is used by my puppet-bolt install.  This is fixed for linux environments but not for windows.

**Comment by jpogran** [comment] 2020-09-29 16:56
This error makes sense now that I know you're using scoop. Scoop is the core of the problem here, it's letting you install Bolt as a user install when bolt is designed as a system-wide install.

Scoop is breaking several parts of bolt:

1. Registry keys Bolt relies on are not created (`HKLM:\Software\Puppet Labs\Bolt`)
These keys are needed by other parts of Bolt
1. Scoop points the user to `bolt.bat` as the entry point
The `bolt.bat` file is a stub file not used by Bolt, and will not have the correct environment set up.
1. The `PuppetBolt` Powershell module is not installed by scoop
This module is the main entry point for Bolt, and without it the user environment is not setup so you have problems with `GEM_HOME` and other environment variables.
1. Scoop installs Bolt to `~\scoop\apps\puppet-bolt\2.29.0` (by default)
This location isn't a problem in of itself, the problem is that it doesn't store the location in the registry or register the program in Windows, which leave parts of Bolt not knowing where things are.

I tried to use the `--global` install switch, but that just installs to `C:\ProgramData\scoop\apps\puppet-bolt\2.29.0` with the same list of modifications as above

Bolt is a system wide install by design and needs to be installed that way. You'll have to use chocolatey or install from an MSI in order to use bolt.

The bolt team will consider this use case in the future, but can't commit to making user-level installs happen at this time.

**Comment by jfastnacht** [comment] 2020-10-12 14:43
It was working fine for me until `2.26.0` (from `1.44.0` when I wrote the initial manifest file for puppet-bolt) without any registry keys, additional env vars or the PowerShell module. The breaking change was the removal of the `lib\ruby\gems\2.5.0\gems` folder in `2.27.0`. Could reproduce it on 2 systems (Win 10).

Is there any issue / pull request with an explanation why it was removed and why it wasn't worth mentioning it in the changelog? (https://github.com/puppetlabs/bolt/blob/main/CHANGELOG.md#bolt-2270-2020-09-08)

**Comment by jpogran** [comment] 2020-10-12 17:43
Thank you for the additional information, this helps me pinpoint the issue. Forgive me, I'm not familiar with scoop and how it differs from other package managers so I did not see this coming from the original post.

The change you're looking for is https://github.com/puppetlabs/bolt-vanagon/commit/f027824c5a35a9599769f51d71871ccd20037f60, which implements a faster method of installing the rubygems we rely on. The commit message goes into detail about the how and the why, but relevant to this discussion is that it uses MSI CustomActions to execute a VBscript to extract a tar file at install time. 

The reason this is important is that it appears scoop [runs](https://github.com/lukesampson/scoop/blob/master/lib/decompress.ps1#L107-L163) an MSI administrative install which extracts the file contents from the MSI instead of running the installer. These files are then 'moved' to the directory scoop wants. The problem is that this is skipping all the installation logic inside the MSI, which means its missing executing the VBscript that extracts the tar file, and thus missing moving all the required gems.

Apologies that this did not make it into the user facing bolt changelog, our packaging code lies in separate repos from our product code. This was a packaging change that did not make it into user facing documentation.

The fact that using just `bolt.bat` was working for you prior to `2.26.0` was an accidental functional behavior. The included PowerShell module is the supported entry point and using just `bolt.bat` is not supported.

**Comment by jfastnacht** [comment] 2020-10-12 22:55
We can probably reproduce both with a custom install script within the manifest, thanks for the reference.

Since this is not an issue of Puppet Bolt but Scoop, you can presumably close this issue in favor of the one in the Scoop Main bucket repository: https://github.com/ScoopInstaller/Main/issues/1364

**Comment by jpogran** [comment] 2020-10-13 16:55
Thanks for the confirmation, I'll close this out then.

**Closed by jpogran** 2020-10-13 16:55 UTC
